services:
  - type: web
    name: chatbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn chatbot:app"
    routes:
      - type: http
        port: 10000